/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_KART_PB_H_INCLUDED
#define PB_KART_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Nested so the generated C types are Status_State / Status_Fault / Status_BrakeMode —
 they must NOT collide with the C++ enum class State/Fault/BrakeMode in control_types.hpp. */
typedef enum _Status_State {
    Status_State_LOCKOUT = 0,
    Status_State_CALIBRATE = 1,
    Status_State_RUN = 2,
    Status_State_FAULT = 3
} Status_State;

typedef enum _Status_BrakeMode {
    Status_BrakeMode_NONE = 0,
    Status_BrakeMode_DYNAMIC = 1,
    Status_BrakeMode_ACTIVE = 2
} Status_BrakeMode;

typedef enum _Status_Fault {
    Status_Fault_NO_FAULT = 0,
    Status_Fault_ESTOP = 1,
    Status_Fault_LVC = 2,
    Status_Fault_NOT_CALIBRATED = 3,
    Status_Fault_ENCODER = 4,
    Status_Fault_ENCODER_DIR = 5,
    Status_Fault_ENCODER_MAD = 6,
    Status_Fault_ENCODER_ABSENT = 7,
    Status_Fault_ENCODER_MAGNET = 8
} Status_Fault;

/* Struct definitions */
/* ── Request (client → kart) ──
 `type` keeps the same verbs as the old JSON protocol: status, get, vals, sysdyn,
 sysinfo, hist, wifiget, padinfo, reboot, padpair, padunpair, calstart, calfinish,
 calcancel, wifiset, set. */
typedef struct _Req {
    char type[16];
    char ssid[33]; /* wifiset */
    char pass[65]; /* wifiset */
    bool enabled; /* wifiset */
    pb_callback_t set; /* set: name/value pairs */
} Req;

typedef struct _ParamVal {
    char name[16];
    pb_size_t which_value;
    union {
        bool bval;
        int32_t ival;
        float fval;
    } value;
} ParamVal;

/* ── Responses (kart → client) ── */
typedef struct _Status {
    Status_State state;
    Status_Fault fault;
    uint32_t faults; /* mask of active conditions (fb:: bits) */
    float vbat;
    int32_t batt_type; /* 0 while detecting, 12 or 24 */
    float batt_lo; /* gauge scale decided on the firmware side */
    float batt_hi;
    float speed_ms; /* VEHICLE speed (m/s, signed — 0 while pivoting) */
    float rpm_l; /* LEFT wheel speed in rpm (signed) */
    float rpm_r; /* RIGHT wheel speed in rpm (signed) */
    float fwd;
    float turn;
    float out_l;
    float out_r;
    Status_BrakeMode brake_mode; /* NONE (traction/freewheel) · DYNAMIC · ACTIVE (PID) */
    bool arming;
    bool btn_start;
    bool pad_conn;
    int32_t pad_batt;
    float pad_x;
    float pad_y;
    float pad_cx;
    float pad_cy;
    float pad_zl;
    float pad_zr;
    float pad_rx2;
    float pad_ry2;
    uint32_t pad_btns;
    int32_t pad_age_ms; /* gamepad heartbeat (age of the last HID report) */
} Status;

typedef struct _ParamMeta {
    pb_callback_t name;
    pb_callback_t desc;
    pb_callback_t cat;
    pb_callback_t help;
    pb_size_t which_value;
    union {
        bool bval;
        int32_t ival;
        float fval;
    } value;
    pb_size_t which_minv;
    union {
        bool bmin;
        int32_t imin;
        float fmin;
    } minv;
    pb_size_t which_maxv;
    union {
        bool bmax;
        int32_t imax;
        float fmax;
    } maxv;
    pb_size_t which_defv;
    union {
        bool bdef;
        int32_t idef;
        float fdef;
    } defv;
} ParamMeta;

typedef struct _Config {
    pb_callback_t params;
} Config;

typedef struct _Vals {
    pb_callback_t params;
} Vals;

/* History: each series = RAW bytes (1 byte/sample, oldest → newest). */
typedef struct _Hist {
    uint32_t dt_fast; /* s between samples (accel/pwm/rpm) */
    uint32_t dt_spd;
    uint32_t dt_batt;
    pb_callback_t accel;
    pb_callback_t pwml;
    pb_callback_t pwmr;
    pb_callback_t rpml;
    pb_callback_t rpmr;
    pb_callback_t spd; /* m/s ×10 */
    pb_callback_t batt; /* V ×10 */
} Hist;

typedef struct _Pad {
    bool conn;
    pb_callback_t name;
    int32_t batt;
    bool calibrated;
    int32_t calstate;
    bool pairing;
} Pad;

typedef struct _Wifi {
    bool enabled;
    pb_callback_t ssid;
    bool connected;
    pb_callback_t ip;
    pb_callback_t error; /* wifiset REFUSED: reason to show; empty = saved */
} Wifi;

typedef struct _Ip6 {
    pb_callback_t addr;
    pb_callback_t type;
} Ip6;

typedef struct _SysInfo {
    pb_callback_t fw_ver;
    pb_callback_t fw_proj;
    pb_callback_t fw_date;
    pb_callback_t idf;
    pb_callback_t chip;
    int32_t cores;
    int32_t rev;
    uint32_t flash_mb;
    int64_t uptime_s;
    uint32_t heap_free;
    uint32_t heap_min;
    pb_callback_t reset;
    pb_callback_t mac_ap;
    pb_callback_t mac_sta;
    pb_callback_t ap_ssid;
    pb_callback_t ip_ap;
    bool sta_en;
    pb_callback_t sta_ssid;
    bool sta_conn;
    pb_callback_t ip_sta;
    pb_callback_t ip6_ap;
    pb_callback_t ip6_sta;
    pb_callback_t mdns; /* mDNS host name WITHOUT the suffix ("kart" → kart.local) */
} SysInfo;

typedef struct _SysDyn {
    int64_t uptime_s;
    uint32_t heap_free;
    uint32_t heap_min;
    uint32_t ledc_fix; /* LEDC clock sentinel */
} SysDyn;

typedef struct _Ok {
    char dummy_field;
} Ok;

/* Envelope: a single frame type on the WebSocket (binary), the oneof does the dispatch. */
typedef struct _Msg {
    pb_size_t which_body;
    union {
        Status status;
        Config config;
        Vals vals;
        Hist hist;
        Pad pad;
        Wifi wifi;
        SysInfo sysinfo;
        SysDyn sysdyn;
        Ok ok;
    } body;
} Msg;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _Status_State_MIN Status_State_LOCKOUT
#define _Status_State_MAX Status_State_FAULT
#define _Status_State_ARRAYSIZE ((Status_State)(Status_State_FAULT+1))

#define _Status_BrakeMode_MIN Status_BrakeMode_NONE
#define _Status_BrakeMode_MAX Status_BrakeMode_ACTIVE
#define _Status_BrakeMode_ARRAYSIZE ((Status_BrakeMode)(Status_BrakeMode_ACTIVE+1))

#define _Status_Fault_MIN Status_Fault_NO_FAULT
#define _Status_Fault_MAX Status_Fault_ENCODER_MAGNET
#define _Status_Fault_ARRAYSIZE ((Status_Fault)(Status_Fault_ENCODER_MAGNET+1))



#define Status_state_ENUMTYPE Status_State
#define Status_fault_ENUMTYPE Status_Fault
#define Status_brake_mode_ENUMTYPE Status_BrakeMode













/* Initializer values for message structs */
#define Req_init_default                         {"", "", "", 0, {{NULL}, NULL}}
#define ParamVal_init_default                    {"", 0, {0}}
#define Status_init_default                      {_Status_State_MIN, _Status_Fault_MIN, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, _Status_BrakeMode_MIN, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define ParamMeta_init_default                   {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, {0}, 0, {0}, 0, {0}, 0, {0}}
#define Config_init_default                      {{{NULL}, NULL}}
#define Vals_init_default                        {{{NULL}, NULL}}
#define Hist_init_default                        {0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define Pad_init_default                         {0, {{NULL}, NULL}, 0, 0, 0, 0}
#define Wifi_init_default                        {0, {{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define Ip6_init_default                         {{{NULL}, NULL}, {{NULL}, NULL}}
#define SysInfo_init_default                     {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define SysDyn_init_default                      {0, 0, 0, 0}
#define Ok_init_default                          {0}
#define Msg_init_default                         {0, {Status_init_default}}
#define Req_init_zero                            {"", "", "", 0, {{NULL}, NULL}}
#define ParamVal_init_zero                       {"", 0, {0}}
#define Status_init_zero                         {_Status_State_MIN, _Status_Fault_MIN, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, _Status_BrakeMode_MIN, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define ParamMeta_init_zero                      {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, {0}, 0, {0}, 0, {0}, 0, {0}}
#define Config_init_zero                         {{{NULL}, NULL}}
#define Vals_init_zero                           {{{NULL}, NULL}}
#define Hist_init_zero                           {0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define Pad_init_zero                            {0, {{NULL}, NULL}, 0, 0, 0, 0}
#define Wifi_init_zero                           {0, {{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define Ip6_init_zero                            {{{NULL}, NULL}, {{NULL}, NULL}}
#define SysInfo_init_zero                        {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define SysDyn_init_zero                         {0, 0, 0, 0}
#define Ok_init_zero                             {0}
#define Msg_init_zero                            {0, {Status_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define Req_type_tag                             1
#define Req_ssid_tag                             2
#define Req_pass_tag                             3
#define Req_enabled_tag                          4
#define Req_set_tag                              5
#define ParamVal_name_tag                        1
#define ParamVal_bval_tag                        2
#define ParamVal_ival_tag                        3
#define ParamVal_fval_tag                        4
#define Status_state_tag                         1
#define Status_fault_tag                         2
#define Status_faults_tag                        3
#define Status_vbat_tag                          4
#define Status_batt_type_tag                     5
#define Status_batt_lo_tag                       6
#define Status_batt_hi_tag                       7
#define Status_speed_ms_tag                      8
#define Status_rpm_l_tag                         9
#define Status_rpm_r_tag                         10
#define Status_fwd_tag                           11
#define Status_turn_tag                          12
#define Status_out_l_tag                         13
#define Status_out_r_tag                         14
#define Status_brake_mode_tag                    15
#define Status_arming_tag                        16
#define Status_btn_start_tag                     17
#define Status_pad_conn_tag                      18
#define Status_pad_batt_tag                      19
#define Status_pad_x_tag                         20
#define Status_pad_y_tag                         21
#define Status_pad_cx_tag                        22
#define Status_pad_cy_tag                        23
#define Status_pad_zl_tag                        24
#define Status_pad_zr_tag                        25
#define Status_pad_rx2_tag                       26
#define Status_pad_ry2_tag                       27
#define Status_pad_btns_tag                      28
#define Status_pad_age_ms_tag                    29
#define ParamMeta_name_tag                       1
#define ParamMeta_desc_tag                       2
#define ParamMeta_cat_tag                        3
#define ParamMeta_help_tag                       4
#define ParamMeta_bval_tag                       8
#define ParamMeta_ival_tag                       9
#define ParamMeta_fval_tag                       10
#define ParamMeta_bmin_tag                       11
#define ParamMeta_imin_tag                       12
#define ParamMeta_fmin_tag                       13
#define ParamMeta_bmax_tag                       14
#define ParamMeta_imax_tag                       15
#define ParamMeta_fmax_tag                       16
#define ParamMeta_bdef_tag                       17
#define ParamMeta_idef_tag                       18
#define ParamMeta_fdef_tag                       19
#define Config_params_tag                        1
#define Vals_params_tag                          1
#define Hist_dt_fast_tag                         1
#define Hist_dt_spd_tag                          2
#define Hist_dt_batt_tag                         3
#define Hist_accel_tag                           4
#define Hist_pwml_tag                            5
#define Hist_pwmr_tag                            6
#define Hist_rpml_tag                            7
#define Hist_rpmr_tag                            8
#define Hist_spd_tag                             9
#define Hist_batt_tag                            10
#define Pad_conn_tag                             1
#define Pad_name_tag                             2
#define Pad_batt_tag                             3
#define Pad_calibrated_tag                       4
#define Pad_calstate_tag                         5
#define Pad_pairing_tag                          6
#define Wifi_enabled_tag                         1
#define Wifi_ssid_tag                            2
#define Wifi_connected_tag                       3
#define Wifi_ip_tag                              4
#define Wifi_error_tag                           5
#define Ip6_addr_tag                             1
#define Ip6_type_tag                             2
#define SysInfo_fw_ver_tag                       1
#define SysInfo_fw_proj_tag                      2
#define SysInfo_fw_date_tag                      3
#define SysInfo_idf_tag                          4
#define SysInfo_chip_tag                         5
#define SysInfo_cores_tag                        6
#define SysInfo_rev_tag                          7
#define SysInfo_flash_mb_tag                     8
#define SysInfo_uptime_s_tag                     9
#define SysInfo_heap_free_tag                    10
#define SysInfo_heap_min_tag                     11
#define SysInfo_reset_tag                        12
#define SysInfo_mac_ap_tag                       13
#define SysInfo_mac_sta_tag                      14
#define SysInfo_ap_ssid_tag                      15
#define SysInfo_ip_ap_tag                        16
#define SysInfo_sta_en_tag                       17
#define SysInfo_sta_ssid_tag                     18
#define SysInfo_sta_conn_tag                     19
#define SysInfo_ip_sta_tag                       20
#define SysInfo_ip6_ap_tag                       21
#define SysInfo_ip6_sta_tag                      22
#define SysInfo_mdns_tag                         23
#define SysDyn_uptime_s_tag                      1
#define SysDyn_heap_free_tag                     2
#define SysDyn_heap_min_tag                      3
#define SysDyn_ledc_fix_tag                      4
#define Msg_status_tag                           1
#define Msg_config_tag                           2
#define Msg_vals_tag                             3
#define Msg_hist_tag                             4
#define Msg_pad_tag                              5
#define Msg_wifi_tag                             6
#define Msg_sysinfo_tag                          7
#define Msg_sysdyn_tag                           8
#define Msg_ok_tag                               9

/* Struct field encoding specification for nanopb */
#define Req_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   type,              1) \
X(a, STATIC,   SINGULAR, STRING,   ssid,              2) \
X(a, STATIC,   SINGULAR, STRING,   pass,              3) \
X(a, STATIC,   SINGULAR, BOOL,     enabled,           4) \
X(a, CALLBACK, REPEATED, MESSAGE,  set,               5)
#define Req_CALLBACK pb_default_field_callback
#define Req_DEFAULT NULL
#define Req_set_MSGTYPE ParamVal

#define ParamVal_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   name,              1) \
X(a, STATIC,   ONEOF,    BOOL,     (value,bval,value.bval),   2) \
X(a, STATIC,   ONEOF,    INT32,    (value,ival,value.ival),   3) \
X(a, STATIC,   ONEOF,    FLOAT,    (value,fval,value.fval),   4)
#define ParamVal_CALLBACK NULL
#define ParamVal_DEFAULT NULL

#define Status_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    state,             1) \
X(a, STATIC,   SINGULAR, UENUM,    fault,             2) \
X(a, STATIC,   SINGULAR, UINT32,   faults,            3) \
X(a, STATIC,   SINGULAR, FLOAT,    vbat,              4) \
X(a, STATIC,   SINGULAR, INT32,    batt_type,         5) \
X(a, STATIC,   SINGULAR, FLOAT,    batt_lo,           6) \
X(a, STATIC,   SINGULAR, FLOAT,    batt_hi,           7) \
X(a, STATIC,   SINGULAR, FLOAT,    speed_ms,          8) \
X(a, STATIC,   SINGULAR, FLOAT,    rpm_l,             9) \
X(a, STATIC,   SINGULAR, FLOAT,    rpm_r,            10) \
X(a, STATIC,   SINGULAR, FLOAT,    fwd,              11) \
X(a, STATIC,   SINGULAR, FLOAT,    turn,             12) \
X(a, STATIC,   SINGULAR, FLOAT,    out_l,            13) \
X(a, STATIC,   SINGULAR, FLOAT,    out_r,            14) \
X(a, STATIC,   SINGULAR, UENUM,    brake_mode,       15) \
X(a, STATIC,   SINGULAR, BOOL,     arming,           16) \
X(a, STATIC,   SINGULAR, BOOL,     btn_start,        17) \
X(a, STATIC,   SINGULAR, BOOL,     pad_conn,         18) \
X(a, STATIC,   SINGULAR, INT32,    pad_batt,         19) \
X(a, STATIC,   SINGULAR, FLOAT,    pad_x,            20) \
X(a, STATIC,   SINGULAR, FLOAT,    pad_y,            21) \
X(a, STATIC,   SINGULAR, FLOAT,    pad_cx,           22) \
X(a, STATIC,   SINGULAR, FLOAT,    pad_cy,           23) \
X(a, STATIC,   SINGULAR, FLOAT,    pad_zl,           24) \
X(a, STATIC,   SINGULAR, FLOAT,    pad_zr,           25) \
X(a, STATIC,   SINGULAR, FLOAT,    pad_rx2,          26) \
X(a, STATIC,   SINGULAR, FLOAT,    pad_ry2,          27) \
X(a, STATIC,   SINGULAR, UINT32,   pad_btns,         28) \
X(a, STATIC,   SINGULAR, INT32,    pad_age_ms,       29)
#define Status_CALLBACK NULL
#define Status_DEFAULT NULL

#define ParamMeta_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, CALLBACK, SINGULAR, STRING,   desc,              2) \
X(a, CALLBACK, SINGULAR, STRING,   cat,               3) \
X(a, CALLBACK, SINGULAR, STRING,   help,              4) \
X(a, STATIC,   ONEOF,    BOOL,     (value,bval,value.bval),   8) \
X(a, STATIC,   ONEOF,    INT32,    (value,ival,value.ival),   9) \
X(a, STATIC,   ONEOF,    FLOAT,    (value,fval,value.fval),  10) \
X(a, STATIC,   ONEOF,    BOOL,     (minv,bmin,minv.bmin),  11) \
X(a, STATIC,   ONEOF,    INT32,    (minv,imin,minv.imin),  12) \
X(a, STATIC,   ONEOF,    FLOAT,    (minv,fmin,minv.fmin),  13) \
X(a, STATIC,   ONEOF,    BOOL,     (maxv,bmax,maxv.bmax),  14) \
X(a, STATIC,   ONEOF,    INT32,    (maxv,imax,maxv.imax),  15) \
X(a, STATIC,   ONEOF,    FLOAT,    (maxv,fmax,maxv.fmax),  16) \
X(a, STATIC,   ONEOF,    BOOL,     (defv,bdef,defv.bdef),  17) \
X(a, STATIC,   ONEOF,    INT32,    (defv,idef,defv.idef),  18) \
X(a, STATIC,   ONEOF,    FLOAT,    (defv,fdef,defv.fdef),  19)
#define ParamMeta_CALLBACK pb_default_field_callback
#define ParamMeta_DEFAULT NULL

#define Config_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  params,            1)
#define Config_CALLBACK pb_default_field_callback
#define Config_DEFAULT NULL
#define Config_params_MSGTYPE ParamMeta

#define Vals_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  params,            1)
#define Vals_CALLBACK pb_default_field_callback
#define Vals_DEFAULT NULL
#define Vals_params_MSGTYPE ParamVal

#define Hist_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   dt_fast,           1) \
X(a, STATIC,   SINGULAR, UINT32,   dt_spd,            2) \
X(a, STATIC,   SINGULAR, UINT32,   dt_batt,           3) \
X(a, CALLBACK, SINGULAR, BYTES,    accel,             4) \
X(a, CALLBACK, SINGULAR, BYTES,    pwml,              5) \
X(a, CALLBACK, SINGULAR, BYTES,    pwmr,              6) \
X(a, CALLBACK, SINGULAR, BYTES,    rpml,              7) \
X(a, CALLBACK, SINGULAR, BYTES,    rpmr,              8) \
X(a, CALLBACK, SINGULAR, BYTES,    spd,               9) \
X(a, CALLBACK, SINGULAR, BYTES,    batt,             10)
#define Hist_CALLBACK pb_default_field_callback
#define Hist_DEFAULT NULL

#define Pad_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     conn,              1) \
X(a, CALLBACK, SINGULAR, STRING,   name,              2) \
X(a, STATIC,   SINGULAR, INT32,    batt,              3) \
X(a, STATIC,   SINGULAR, BOOL,     calibrated,        4) \
X(a, STATIC,   SINGULAR, INT32,    calstate,          5) \
X(a, STATIC,   SINGULAR, BOOL,     pairing,           6)
#define Pad_CALLBACK pb_default_field_callback
#define Pad_DEFAULT NULL

#define Wifi_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     enabled,           1) \
X(a, CALLBACK, SINGULAR, STRING,   ssid,              2) \
X(a, STATIC,   SINGULAR, BOOL,     connected,         3) \
X(a, CALLBACK, SINGULAR, STRING,   ip,                4) \
X(a, CALLBACK, SINGULAR, STRING,   error,             5)
#define Wifi_CALLBACK pb_default_field_callback
#define Wifi_DEFAULT NULL

#define Ip6_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   addr,              1) \
X(a, CALLBACK, SINGULAR, STRING,   type,              2)
#define Ip6_CALLBACK pb_default_field_callback
#define Ip6_DEFAULT NULL

#define SysInfo_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   fw_ver,            1) \
X(a, CALLBACK, SINGULAR, STRING,   fw_proj,           2) \
X(a, CALLBACK, SINGULAR, STRING,   fw_date,           3) \
X(a, CALLBACK, SINGULAR, STRING,   idf,               4) \
X(a, CALLBACK, SINGULAR, STRING,   chip,              5) \
X(a, STATIC,   SINGULAR, INT32,    cores,             6) \
X(a, STATIC,   SINGULAR, INT32,    rev,               7) \
X(a, STATIC,   SINGULAR, UINT32,   flash_mb,          8) \
X(a, STATIC,   SINGULAR, INT64,    uptime_s,          9) \
X(a, STATIC,   SINGULAR, UINT32,   heap_free,        10) \
X(a, STATIC,   SINGULAR, UINT32,   heap_min,         11) \
X(a, CALLBACK, SINGULAR, STRING,   reset,            12) \
X(a, CALLBACK, SINGULAR, STRING,   mac_ap,           13) \
X(a, CALLBACK, SINGULAR, STRING,   mac_sta,          14) \
X(a, CALLBACK, SINGULAR, STRING,   ap_ssid,          15) \
X(a, CALLBACK, SINGULAR, STRING,   ip_ap,            16) \
X(a, STATIC,   SINGULAR, BOOL,     sta_en,           17) \
X(a, CALLBACK, SINGULAR, STRING,   sta_ssid,         18) \
X(a, STATIC,   SINGULAR, BOOL,     sta_conn,         19) \
X(a, CALLBACK, SINGULAR, STRING,   ip_sta,           20) \
X(a, CALLBACK, REPEATED, MESSAGE,  ip6_ap,           21) \
X(a, CALLBACK, REPEATED, MESSAGE,  ip6_sta,          22) \
X(a, CALLBACK, SINGULAR, STRING,   mdns,             23)
#define SysInfo_CALLBACK pb_default_field_callback
#define SysInfo_DEFAULT NULL
#define SysInfo_ip6_ap_MSGTYPE Ip6
#define SysInfo_ip6_sta_MSGTYPE Ip6

#define SysDyn_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    uptime_s,          1) \
X(a, STATIC,   SINGULAR, UINT32,   heap_free,         2) \
X(a, STATIC,   SINGULAR, UINT32,   heap_min,          3) \
X(a, STATIC,   SINGULAR, UINT32,   ledc_fix,          4)
#define SysDyn_CALLBACK NULL
#define SysDyn_DEFAULT NULL

#define Ok_FIELDLIST(X, a) \

#define Ok_CALLBACK NULL
#define Ok_DEFAULT NULL

#define Msg_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,status,body.status),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,config,body.config),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,vals,body.vals),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,hist,body.hist),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,pad,body.pad),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,wifi,body.wifi),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,sysinfo,body.sysinfo),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,sysdyn,body.sysdyn),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,ok,body.ok),   9)
#define Msg_CALLBACK NULL
#define Msg_DEFAULT NULL
#define Msg_body_status_MSGTYPE Status
#define Msg_body_config_MSGTYPE Config
#define Msg_body_vals_MSGTYPE Vals
#define Msg_body_hist_MSGTYPE Hist
#define Msg_body_pad_MSGTYPE Pad
#define Msg_body_wifi_MSGTYPE Wifi
#define Msg_body_sysinfo_MSGTYPE SysInfo
#define Msg_body_sysdyn_MSGTYPE SysDyn
#define Msg_body_ok_MSGTYPE Ok

extern const pb_msgdesc_t Req_msg;
extern const pb_msgdesc_t ParamVal_msg;
extern const pb_msgdesc_t Status_msg;
extern const pb_msgdesc_t ParamMeta_msg;
extern const pb_msgdesc_t Config_msg;
extern const pb_msgdesc_t Vals_msg;
extern const pb_msgdesc_t Hist_msg;
extern const pb_msgdesc_t Pad_msg;
extern const pb_msgdesc_t Wifi_msg;
extern const pb_msgdesc_t Ip6_msg;
extern const pb_msgdesc_t SysInfo_msg;
extern const pb_msgdesc_t SysDyn_msg;
extern const pb_msgdesc_t Ok_msg;
extern const pb_msgdesc_t Msg_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Req_fields &Req_msg
#define ParamVal_fields &ParamVal_msg
#define Status_fields &Status_msg
#define ParamMeta_fields &ParamMeta_msg
#define Config_fields &Config_msg
#define Vals_fields &Vals_msg
#define Hist_fields &Hist_msg
#define Pad_fields &Pad_msg
#define Wifi_fields &Wifi_msg
#define Ip6_fields &Ip6_msg
#define SysInfo_fields &SysInfo_msg
#define SysDyn_fields &SysDyn_msg
#define Ok_fields &Ok_msg
#define Msg_fields &Msg_msg

/* Maximum encoded size of messages (where known) */
/* Req_size depends on runtime parameters */
/* ParamMeta_size depends on runtime parameters */
/* Config_size depends on runtime parameters */
/* Vals_size depends on runtime parameters */
/* Hist_size depends on runtime parameters */
/* Pad_size depends on runtime parameters */
/* Wifi_size depends on runtime parameters */
/* Ip6_size depends on runtime parameters */
/* SysInfo_size depends on runtime parameters */
/* Msg_size depends on runtime parameters */
#define KART_PB_H_MAX_SIZE                       Status_size
#define Ok_size                                  0
#define ParamVal_size                            28
#define Status_size                              161
#define SysDyn_size                              29

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
