/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "kart.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Req, Req, AUTO)


PB_BIND(ParamVal, ParamVal, AUTO)


PB_BIND(Status, Status, AUTO)


PB_BIND(ParamMeta, ParamMeta, AUTO)


PB_BIND(Config, Config, AUTO)


PB_BIND(Vals, Vals, AUTO)


PB_BIND(Hist, Hist, AUTO)


PB_BIND(Pad, Pad, AUTO)


PB_BIND(Wifi, Wifi, AUTO)


PB_BIND(Ip6, Ip6, AUTO)


PB_BIND(SysInfo, SysInfo, 2)


PB_BIND(SysDyn, SysDyn, AUTO)


PB_BIND(Ok, Ok, AUTO)


PB_BIND(EvlogEntry, EvlogEntry, AUTO)


PB_BIND(Evlog, Evlog, AUTO)


PB_BIND(Msg, Msg, 2)









